language: ruby
env:
  - "RAILS_VERSION=3.2.16"
  - "RAILS_VERSION=4.0.2"

rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - cd test/dummy
  - RAILS_ENV=test rake db:create db:migrate
  - RAILS_ENV=remote rake db:create db:migrate
script:
  - cd ${TRAVIS_BUILD_DIR}
  - rake test





